version: '3'
services:
    queridas:
        build: .
        command: bash
        volumes:
            - ./:/usr/queridas/
        links:
            - db
    db:
        image: postgres:10.2-alpine
        restart: always
        environment:
            PGDATA: /var/lib/postgresql/data/fatos/
            POSTGRES_PASSWORD: must be changed.
        volumes:
            - ./data/postgresql/:/var/lib/postgresql/data/fatos/

