version: '3'
services:
    queridas:
        build: .
        volumes:
            - ./:/usr/queridas/
        links:
            - db
        environment:
            DEBUG: 0
    db:
        image: postgres:10.2-alpine
        restart: always
        environment:
            POSTGRES_DB: fatos
            PGDATA: /var/lib/postgresql/data/fatos/
            POSTGRES_PASSWORD: must be changed.
        ports:
            - 5432:5432
        volumes:
            - ./data/postgresql/:/var/lib/postgresql/data/fatos/

