version: '2'
services:
    queridas:
        build: .
        # The volume below overrides the COPY commands from the Dockerfile.
        # So, install node dependencies again before serving.
        command: bash -c "npm install && aranhas --help"
        volumes:
            - '../memoria-politica/:/usr/memoria-politica/'
            - ./:/usr/queridas/
        links:
            - db
        environment:
            DEBUG: 0
    db:
        image: postgres:10.2-alpine
        restart: always
        environment:
            POSTGRES_DB: fatos
            PGDATA: /var/lib/postgresql/data/fatos/
            POSTGRES_PASSWORD: must be changed.
        ports:
            - 5433:5432
        volumes:
            - /var/lib/postgresql/data/fatos/
