version: '3'
services:
    xeretas:
        build: .
        command: bash
        volumes:
            - ./:/usr/xeretas/
        links:
            - db
    db:
        image: postgres:10.2-alpine
        restart: always
        environment:
            PGDATA: /var/lib/postgresql/data/re7
            POSTGRES_USER: xereta
            POSTGRES_PASSWORD: must be changed.
        volumes:
            - ./data/postgresql/:/var/lib/postgresql/data/re7/

